WebTest/Project WebApps/Project_6/bestHomePage/config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks

  resources :settings

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :weathers

  resources :users

  resources :notes

  get 'main/home'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  root to: 'main#home', show: 'main'
  match 'main/update_note' => 'main#update_note', :via => [:post]

end

WebTest/Project WebApps/Project_6/bestHomePage/app/models/weather.rb
class Weather < ActiveRecord::Base
	validates :location, presence: true, uniqueness: true
	
	validates :high, presence: true
	validates :low, presence: true
	validates :condition, presence: true
	validates :wind_speed, presence: true
  validates :loc_name, presence: true
  validates :sunrise, presence: true
  validates :sunset, presence: true
  has_many :users
end

WebTest/Project WebApps/Project_6/bestHomePage/app/controllers/weathers_controller.rb
class WeathersController < ApplicationController
  before_action :set_weather, only: [:show, :edit, :update, :destroy]

  # GET /weathers
  # GET /weathers.json
  def index
    @weathers = Weather.all
  end

  # GET /weathers/1
  # GET /weathers/1.json
  def show
  end

  # GET /weathers/new
  def new
    @weather = Weather.new
  end

  # GET /weathers/1/edit
  def edit
  end

  # POST /weathers
  # POST /weathers.json
  def create
    @weather = Weather.new(weather_params)

    respond_to do |format|
      if @weather.save
        format.html { redirect_to @weather, notice: 'Weather was successfully created.' }
        format.json { render :show, status: :created, location: @weather }
      else
        format.html { render :new }
        format.json { render json: @weather.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weathers/1
  # PATCH/PUT /weathers/1.json
  def update
    respond_to do |format|
      if @weather.update(weather_params)
        format.html { redirect_to @weather, notice: 'Weather was successfully updated.' }
        format.json { render :show, status: :ok, location: @weather }
      else
        format.html { render :edit }
        format.json { render json: @weather.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weathers/1
  # DELETE /weathers/1.json
  def destroy
    @weather.destroy
    respond_to do |format|
      format.html { redirect_to weathers_url, notice: 'Weather was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weather
      @weather = Weather.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weather_params
      params.require(:weather).permit(:location, :high, :low, :condition, :wind_speed, :loc_name, :sunrise, :sunset)
    end
end

WebTest/Project WebApps/Project_6/bestHomePage/app/helpers/weathers_helper.rb
module WeathersHelper
end

WebTest/Project WebApps/Project_6/bestHomePage/app/views/weathers/_form.html.erb
<%= form_for(@weather) do |f| %>
  <% if @weather.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weather.errors.count, "error") %> prohibited this weather from being saved:</h2>

      <ul>
      <% @weather.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %><br>
    <%= f.number_field :location %>
  </div>
  <div class="field">
    <%= f.label :high %><br>
    <%= f.number_field :high %>
  </div>
  <div class="field">
    <%= f.label :low %><br>
    <%= f.number_field :low %>
  </div>
  <div class="field">
    <%= f.label :condition %><br>
    <%= f.text_field :condition %>
  </div>
  <div class="field">
    <%= f.label :wind_speed %><br>
    <%= f.number_field :wind_speed %>
  </div>
  <div class="field">
    <%= f.label :loc_name %><br>
    <%= f.text_field :loc_name %>
  </div>
  <div class="field">
    <%= f.label :sunrise %><br>
    <%= f.number_field :sunrise %>
  </div>
  <div class="field">
    <%= f.label :sunset %><br>
    <%= f.number_field :sunset %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

WebTest/Project WebApps/Project_6/bestHomePage/app/views/weathers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @weather.location %>
</p>

<p>
  <strong>High:</strong>
  <%= @weather.high %>
</p>

<p>
  <strong>Low:</strong>
  <%= @weather.low %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @weather.condition %>
</p>

<p>
  <strong>Wind speed:</strong>
  <%= @weather.wind_speed %>
</p>

<p>
  <strong>Loc name:</strong>
  <%= @weather.loc_name %>
</p>

<p>
  <strong>Sunrise:</strong>
  <%= @weather.sunrise %>
</p>

<p>
  <strong>Sunset:</strong>
  <%= @weather.sunset %>
</p>

<%= link_to 'Edit', edit_weather_path(@weather) %> |
<%= link_to 'Back', weathers_path %>