WebTest/Project WebApps/Project_6/bestHomePage/config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks

  resources :settings

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :weathers

  resources :users

  resources :notes

  get 'main/home'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  root to: 'main#home', show: 'main'
  match 'main/update_note' => 'main#update_note', :via => [:post]

end

WebTest/Project WebApps/Project_6/bestHomePage/app/controllers/main_controller.rb
require 'json'
require 'net/http'
class MainController < ApplicationController

  
  
  def home
  	@user = User.find_by(user_name: session[:user_id])
  	if (@user)
  		@location = @user.location #user exists
  	
  	
	  	@note = Note.find_by(user_name: session[:user_id]).note
	  	@bookmark = Bookmark.where(user_name: session[:user_id])
	  	
	  	@weather = Weather.find_by location: @location
	  	@time = Time.now.hour * 100 + Time.now.min
	  	if (@weather)
	  	@weather_time = ((@weather.updated_at.to_formatted_s[11] + @weather.updated_at.to_formatted_s[12]) * 100 + 
	  	    (@weather.updated_at.to_formatted_s[14] + @weather.updated_at.to_formatted_s[15])).to_i
	  	@time = @time - @weather_time
	  	if @time > 100
		  	  # has been more than one hour since weather was updated 
		  	@url = URI('http://api.openweathermap.org/data/2.5/weather?zip=' + @location.to_s + ',us')
			  @result = Net::HTTP.get(@url)
			  @w_hash = JSON.parse(@result)
			  s = Weather.new location: @user.location.to_s,  high: @w_hash["main"]["temp_max"],
			    low: @w_hash["main"]["temp_min"], condition: @w_hash["weather"][0]["main"],	wind_speed: @w_hash["wind"]["speed"],
			    loc_name: @w_hash["name"], sunrise: @w_hash["sys"]["sunrise"], sunset: @w_hash["sys"]["sunset"]
			  s.save
			end
	  	end   
  	end
  end
  

  def update_note

@note = Note.find_by(user_name: session[:user_id])

  if @note.update_attributes(params[:note])
    format.html { redirect_to @note, :notice => 'Note was successfully updated.' }
    @updated = "true"
    format.js
  else
    format.html { render :action => "edit" }
    @updated = "false"
    format.js
  end
 end  

  
end

WebTest/Project WebApps/Project_6/bestHomePage/app/helpers/main_helper.rb
module MainHelper
end

WebTest/Project WebApps/Project_6/bestHomePage/app/views/main/home.html.erb
<% if !(session[:user_id]) %>
<!-- Default layout: No one is logged in -->
	<div id="header">
	  <div class="primary btn pretty"><%= link_to 'Sign In', login_path %></div>
	  <div class="secondary btn pretty"><%= link_to 'Sign Up', new_user_path %></div>
	  <div style="text-align: center;">
	    <%= image_tag("bestHomePageLogo.png", :alt =>"bestHomePageLogo") %>
	  </div>
	</div>

	<div id="body">
	<div class="row navbar" id="nav1">
  		<ul class="four columns" style="margin-right:auto;margin-left:auto;">
    		<li ><%=link_to "Ohio State Home Page", "http://www.osu.edu", :target => '_blank' %></li>
	    	<li ><%=link_to "Carmen", "http://carmen.osu.edu", :target => '_blank' %></li>
	    	<li ><%=link_to "Buckeyelink", "http://buckeyelink.osu.edu", :target => '_blank' %></li>
	    	<li ><%=link_to "Buckeyemail", "http://buckeyemail.osu.edu", :target => '_blank' %></li>
	  	</ul>
	</div>
	
	<br>
	<br>
	<br>
	<div class="twelve colgrid" style="text-align: center">
	  <div class="row">
	    <div class="eight columns" id="weather">
	      <p>
	        <table>
	          <thead>
	            <tr>
	              <th>Weather Unavailable</th>
	            </tr>
	          </thead>
	          <tbody>
	            <tr>
	              <td>Please Login to Provide Location</td>
	            </tr>
	          </tbody>
	        </table>
	      </p>
	    </div>
	    <div class="four columns" id="note">
	      <textarea id="area" style="width:300px; height:300px;" placeholder="These notes won't be saved!
	      Login to enable saving your notes!"></textarea>
	      <div id="clear" class="primary btn pretty"><a href="#">Clear</a></div>
	      <div class="secondary btn pretty"><a href="#">Save</div>
	    </div>
	    
	  </div>
	</div>
	</div>

<% else %>
<!-- ---------User is logged in--------- -->
<div id="header">
		<div class="primary btn pretty"><%= link_to "#{session[:user_id]}", edit_setting_path(Setting.find_by(user_name: session[:user_id])) %></div>
		<div class="secondary btn pretty"><%= link_to 'Log out',logout_path, :method => :delete  %></div>
		
	  <div style="text-align: center;">
	    <%= image_tag("bestHomePageLogo.png", :alt =>"bestHomePageLogo") %>
	  </div>
	</div>

	<div id="body">
	<div class="row navbar" id="nav1">
		<ul class="four columns" style="margin-right:auto;margin-left:auto;">
			<% @bookmark.each do |b| %>
				<li><%= link_to b.title, b.url, :target => '_blank'%></li>
			<% end %>
		</ul>
	</div>
	
	<br>
	<br>
	<br>
	<div class="twelve colgrid" style="text-align: center">
	  <div class="row">
	    <div class="eight columns" id="weather">
	    <% if @weather %>
	    <% @w_data = Weather.find_by(location: @location) %>
	        <table>
	          <thead>
	            <tr>
	              <th>Weather for <%= @w_data.loc_name %>, <%= @location %></th>
	            </tr>
	          </thead>
	          <tbody>
				<tr>
					<td></td>
					<td>High(f): </br><%= @w_data.high %></td>
					<td>Low(f): </br><%= @w_data.low %></td>
					<td>Condition: </br><%= @w_data.condition %></td>
				</tr>
				<tr>	
					<td></td>
					<td>Wind: </br><%=(@w_data.wind_speed*2.23693629).round %>mph</td>
					<!-- unix time to ascii time -->
					<% @Sunrise = Time.at(@w_data.sunrise) %>
					<% @Sunset = Time.at(@w_data.sunset) %>
					<!-- format times -->
					<td>Sunrise: </br><%= @Sunrise.strftime("%I:%M%p")%></td>
					<td>Sunset: </br><%=  @Sunset.strftime("%I:%M%p")%></td>
				</tr>
	          </tbody>
	        </table>
	    <% else %>
	    <table>
        <thead>
	        <tr>
           <th>Unable to generate weather for  <%= @location %></th>
	        </tr>
	      </thead>
	    </table>
	    <% end %>
	    </div>
	    <%= form_tag({:controller=>'main',:action=>'update_note'},:method=>:post,:id=>"update_note",:name=>'note_form',:remote=>true) do %>
	    <div class="four columns" id="note">
	      <textarea id="area" style="width:300px; height:300px;" placeholder="Your notes starts here"><%= @note %></textarea>
	      <div id="clear" class="primary btn pretty"><a href="#">Clear</a></div>
	      <div class="secondary btn pretty"><%= submit_tag 'Save' %></div>
	    </div>
	   <% end %>
	  <div id="updated">

	  </div>
	  </div>
	</div>
</div>

<% end %>