WebTest/Project WebApps/Project_6/bestHomePage/config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks

  resources :settings

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :weathers

  resources :users

  resources :notes

  get 'main/home'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  root to: 'main#home', show: 'main'
  match 'main/update_note' => 'main#update_note', :via => [:post]

end

WebTest/Project WebApps/Project_6/bestHomePage/app/models/setting.rb
class Setting < ActiveRecord::Base
	belongs_to :user, :foreign_key => 'user_name'
end

WebTest/Project WebApps/Project_6/bestHomePage/app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: [:show, :edit, :update, :destroy]
  # GET /settings
  # GET /settings.json
  @colors =[['White','white'],['Black','black'],['Blue','blue'],['Green','green'],['Yellow','yellow'],['Orange','orange'],['Purple','purple']]
  @sizes = [['8','8'],['10','10'],['12','12'],['14','14'],['16','16'],['18','18'],['20','20']]
  @fonts = [['Arial','Arial'],['Helvetica','Helvetica'],['Times New Roman','Times New Roman'],['Courier New','Courier New']]
  def index
    @settings = Setting.all
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Setting was successfully created.' }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1
  # PATCH/PUT /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to main_home_path, notice: 'Setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to settings_url, notice: 'Setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.require(:setting).permit(:background, :fontSize, :fontColor, :fontFamily, :user_name)
    end
end

WebTest/Project WebApps/Project_6/bestHomePage/app/helpers/settings_helper.rb
module SettingsHelper
end

WebTest/Project WebApps/Project_6/bestHomePage/app/views/settings/_form.html.erb
<%= form_for(@setting) do |f| %>
  <% if @setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% @setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>

  <div class="field">
    <%= f.label :background %><br>
    <%= f.text_field :background %>
  </div>
  <div class="field">
    <%= f.label :fontSize %><br>
    <%= f.number_field :fontSize %>
  </div>
  <div class="field">
    <%= f.label :fontColor %><br>
    <%= f.text_field :fontColor %>
  </div>
  <div class="field">
    <%= f.label :fontFamily %><br>
    <%= f.text_field :fontFamily %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

WebTest/Project WebApps/Project_6/bestHomePage/app/views/settings/edit.html.erb
<h3 align="center">Settings</h3>
<section class="pill tabs">
    <ul class="tab-nav">
        <li class="active"><a href="#">User Interface</a></li>
        <li><a href="#">Location/Password</a></li>
        <li><a href="#">Bookmarks</a></li>
    </ul>
    <div class="tab-content active">
    	<%= form_for(Setting.find_by(user_name: session[:user_id])) do |f| %>
        <h4>Background Color</h4>
		<li class = "field">
			<div class="picker">
				<%= f.select :background, options_for_select([['Grey','grey'],['White','white'],['Black','black'],['Blue','blue'],['Green','green'],['Yellow','yellow'],['Orange','orange'],['Purple','purple']]) %>
			</div>
		</li>

		<br />
		 <h4>Font Color</h4>
		<li class = "field">
			<div class="picker">
				<%= f.select :fontColor, options_for_select([['Black','black'],['White','white'],['Grey','grey'],['Blue','blue'],['Green','green'],['Yellow','yellow'],['Orange','orange'],['Purple','purple']]) %>
			</div>
		</li>
		<br />
		<h4>Font Size</h4>
		<li class = "field">
			<div class="picker">
				<%= f.select :fontSize, options_for_select([['8','8'],['10','10'],['12','12'],['14','14'],['16','16'],['18','18'],['20','20']]) %>
			</div>
		</li>
		<br />
		<h4>Font Family</h4>
		<li class = "field">
			<div class="picker">
				<%= f.select :fontFamily, options_for_select([['Arial','Arial'],['Helvetica','Helvetica'],['Times New Roman','Times New Roman'],['Courier New','Courier New']]) %>
			</div>
		</li>
			<div class="actions">
				<li class="medium default btn pretty"><%= f.submit "Update" %></li>
			</div>
		<% end %>
    </div>
    
    <div class="tab-content"
        <li class="danger alert" style="font-size: 20px;">Note: All fields must be filled out properly!</li><br />
        <%= form_for(l= User.find_by(user_name: session[:user_id])) do |f| %>
        	<% if l.errors.any? %>
				    <div id="error_explanation">
					    <h2><%= pluralize(l.errors.count, "error") %> prohibited this password/location from being saved:</h2>
					    <ul>
						    <% l.errors.full_messages.each do |message| %>
							    <li><%= message %></li>
						    <% end %>
					    </ul>
				    </div>
			    <% end %>
			
			<div class="field">
				<%= f.text_field :location %>
			</div>
			<div class="field">
        <li class="info badge">Enter current password or new password</li>
      		<%= f.password_field :password %>
    	</div>
			<div class="field">
      	<li class="info badge">Confirm Password</li>
      		<%= f.password_field :password_confirmation %>
    	</div>
			<div class="actions">
				<li class="medium default btn pretty"><%= f.submit "Update" %></li>
			</div>
		  <% end %>
    </div>

    <div class="tab-content">
		<ul>
			<li class="danger alert" style="font-size: 20px;">Note: URL must have 'http://' prefix!</li><br />
			<% Bookmark.where(user_name: session[:user_id]).each do |b| %>
				<%= form_for(b) do |f| %>
  					<% if b.errors.any? %>
    					<div id="error_explanation">
      						<h2><%= pluralize(b.errors.count, "error") %> prohibited this bookmark from being saved:</h2>
     						 <ul>
      						<% b.errors.full_messages.each do |message| %>
        						<li><%= message %></li>
      						<% end %>
      						</ul>
   						</div>
  					<% end %>
					<div class="field">
					  <li class="info badge">Title</li>
				    <%= f.text_field :title %>
					</div>
					<div class="field">
					    <li class="info badge">URL</li>
					    <%= f.text_field :url %>
					</div>
					<div class="actions">
					    <li class="small default btn pretty"><%= f.submit "Update Bookmark" %></li>
					</div>
				<% end %>
			<% end %> 
		</ul>

    </div>

</section>

<div class="danger btn pretty"><%= link_to 'Home', main_home_path %>

WebTest/Project WebApps/Project_6/bestHomePage/app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @setting.user_name%>
</p>

<p>
  <strong>Background:</strong>
  <%= @setting.background %>
</p>

<p>
  <strong>Fontsize:</strong>
  <%= @setting.fontSize %>
</p>

<p>
  <strong>Fontcolor:</strong>
  <%= @setting.fontColor %>
</p>

<p>
  <strong>Fontfamily:</strong>
  <%= @setting.fontFamily %>
</p>

<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>